# Site settings
title: "Alex Laverty"
subtitle: ""
author: Alex Laverty
email: alaverty@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Alex Laverty
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alaverty.github.io" # the base hostname & protocol for your site
twitter_username: alaverty
github_username:  alexlaverty

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->
category_dir: category
permalink: /:categories/:slug
